"""initial schema

Revision ID: 7488a0137a83
Revises:
Create Date: 2026-06-17 00:00:00.000000

This migration captures the full schema as it exists in production
today (built historically via Base.metadata.create_all() plus ad-hoc
ALTER TABLE statements in app startup). It is written by hand, not
autogenerated, because there is no working dev DB/venv available in
this environment to run `alembic revision --autogenerate` against.

For databases that already have this schema (i.e. every existing
deployment), do NOT run `alembic upgrade head` from scratch — it will
try to create tables that already exist. Instead run:

    alembic stamp 7488a0137a83

to mark the DB as already being at this revision, then
`alembic upgrade head` to apply anything after it.

For a brand new, empty database, `alembic upgrade head` will create
the full schema from zero.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7488a0137a83'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'warehouses',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('type', sa.String(length=20), nullable=False),
        sa.Column('country', sa.String(length=50), nullable=True),
        sa.Column('city', sa.String(length=100), nullable=True),
        sa.Column('phone', sa.String(length=50), nullable=False),
        sa.Column('region', sa.String(length=255), nullable=False),
        sa.Column('address', sa.Text(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now()),
    )

    op.create_table(
        'staff_users',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('full_name', sa.String(length=255), nullable=False),
        sa.Column('login', sa.String(length=100), nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=False),
        sa.Column('role', sa.String(length=20), nullable=False),
        sa.Column('avatar_url', sa.String(length=500), nullable=True),
        sa.Column('permissions', sa.Text(), nullable=True),
        sa.Column('warehouse_id', sa.Integer(), sa.ForeignKey('warehouses.id'), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now()),
        sa.Column('password_changed_at', sa.DateTime(), server_default=sa.func.now()),
        sa.UniqueConstraint('login', name='uq_staff_users_login'),
    )

    op.create_table(
        'clients',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('telegram_id', sa.BigInteger(), nullable=False),
        sa.Column('tps_code', sa.String(length=20), nullable=False),
        sa.Column('full_name', sa.String(length=255), nullable=False),
        sa.Column('phone', sa.String(length=20), nullable=False),
        sa.Column('address', sa.Text(), nullable=True),
        sa.Column('lang', sa.String(length=5), nullable=False, server_default='ru'),
        sa.Column('status', sa.String(length=20), nullable=False, server_default='active'),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now()),
        sa.Column('last_activity_at', sa.DateTime(), nullable=True),
        sa.UniqueConstraint('telegram_id', name='uq_clients_telegram_id'),
        sa.UniqueConstraint('tps_code', name='uq_clients_tps_code'),
    )
    op.create_index('ix_clients_telegram_id', 'clients', ['telegram_id'])
    op.create_index('ix_clients_tps_code', 'clients', ['tps_code'])
    op.create_index('ix_clients_phone', 'clients', ['phone'])
    op.create_index('ix_clients_full_name', 'clients', ['full_name'])

    op.create_table(
        'tariffs',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('method', sa.String(length=20), nullable=False),
        sa.Column('price_per_kg', sa.Numeric(10, 2), nullable=False),
        sa.Column('price_per_m3', sa.Numeric(10, 2), nullable=True),
        sa.Column('currency', sa.String(length=10), nullable=False, server_default='TJS'),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('created_by', sa.Integer(), sa.ForeignKey('staff_users.id'), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now()),
    )

    op.create_table(
        'parcels_china',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('track_id', sa.String(length=100), nullable=False),
        sa.Column('warehouse_id', sa.Integer(), sa.ForeignKey('warehouses.id'), nullable=True),
        sa.Column('created_by', sa.Integer(), sa.ForeignKey('staff_users.id'), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now()),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column('deleted_by', sa.Integer(), sa.ForeignKey('staff_users.id'), nullable=True),
        sa.UniqueConstraint('track_id', name='uq_parcels_china_track_id'),
    )
    op.create_index('ix_parcels_china_track_id', 'parcels_china', ['track_id'], unique=True)
    op.create_index('ix_parcels_china_created_at', 'parcels_china', ['created_at'])

    op.create_table(
        'parcels_dushanbe',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('track_id', sa.String(length=100), nullable=False),
        sa.Column('client_id', sa.Integer(), sa.ForeignKey('clients.id'), nullable=False),
        sa.Column('status', sa.String(length=30), nullable=False, server_default='received_dushanbe'),
        sa.Column('weight_kg', sa.Numeric(10, 3), nullable=False),
        sa.Column('volume_m3', sa.Numeric(10, 4), nullable=True),
        sa.Column('delivery_method', sa.String(length=20), nullable=False),
        sa.Column('warehouse_id', sa.Integer(), sa.ForeignKey('warehouses.id'), nullable=True),
        sa.Column('amount_due', sa.Numeric(10, 2), nullable=True),
        sa.Column('tariff_snapshot', sa.Numeric(10, 2), nullable=True),
        sa.Column('has_china_registration', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('comment', sa.Text(), nullable=True),
        sa.Column('shelf', sa.String(length=20), nullable=True),
        sa.Column('notified_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.Integer(), sa.ForeignKey('staff_users.id'), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now()),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column('deleted_by', sa.Integer(), sa.ForeignKey('staff_users.id'), nullable=True),
        sa.UniqueConstraint('track_id', name='uq_parcels_dushanbe_track_id'),
    )
    op.create_index('ix_parcels_dushanbe_track_id', 'parcels_dushanbe', ['track_id'], unique=True)
    op.create_index('ix_parcels_dushanbe_client_id', 'parcels_dushanbe', ['client_id'])
    op.create_index('ix_parcels_dushanbe_status', 'parcels_dushanbe', ['status'])
    op.create_index('ix_parcels_dushanbe_created_at', 'parcels_dushanbe', ['created_at'])
    op.create_index('ix_parcels_dushanbe_delivery_method', 'parcels_dushanbe', ['delivery_method'])

    op.create_table(
        'unresolved_parcels',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('track_id', sa.String(length=100), nullable=False),
        sa.Column('raw_tps_code', sa.String(length=50), nullable=False),
        sa.Column('weight_kg', sa.Numeric(10, 3), nullable=True),
        sa.Column('volume_m3', sa.Numeric(10, 4), nullable=True),
        sa.Column('delivery_method', sa.String(length=20), nullable=True),
        sa.Column('comment', sa.Text(), nullable=True),
        sa.Column('resolved', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('resolved_parcel_id', sa.Integer(), sa.ForeignKey('parcels_dushanbe.id'), nullable=True),
        sa.Column('created_by', sa.Integer(), sa.ForeignKey('staff_users.id'), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now()),
    )

    op.create_table(
        'issuance_orders',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('client_id', sa.Integer(), sa.ForeignKey('clients.id'), nullable=False),
        sa.Column('staff_id', sa.Integer(), sa.ForeignKey('staff_users.id'), nullable=False),
        sa.Column('total_weight', sa.Numeric(10, 3), nullable=False),
        sa.Column('total_amount', sa.Numeric(10, 2), nullable=False),
        sa.Column('payment_status', sa.String(length=20), nullable=False),
        sa.Column('payment_method', sa.String(length=20), nullable=True),
        sa.Column('comment', sa.Text(), nullable=True),
        sa.Column('issued_at', sa.DateTime(), server_default=sa.func.now()),
    )

    op.create_table(
        'issuance_items',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('issuance_order_id', sa.Integer(), sa.ForeignKey('issuance_orders.id'), nullable=False),
        sa.Column('parcel_id', sa.Integer(), sa.ForeignKey('parcels_dushanbe.id'), nullable=False),
        sa.Column('weight_kg', sa.Numeric(10, 3), nullable=False),
        sa.Column('volume_m3', sa.Numeric(10, 4), nullable=True),
        sa.Column('delivery_method', sa.String(length=20), nullable=False),
        sa.Column('tariff_applied', sa.Numeric(10, 2), nullable=False),
        sa.Column('amount', sa.Numeric(10, 2), nullable=False),
    )

    op.create_table(
        'notification_logs',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('client_id', sa.Integer(), sa.ForeignKey('clients.id'), nullable=False),
        sa.Column('parcel_id', sa.Integer(), sa.ForeignKey('parcels_dushanbe.id'), nullable=True),
        sa.Column('notification_type', sa.String(length=50), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('error', sa.Text(), nullable=True),
        sa.Column('sent_at', sa.DateTime(), server_default=sa.func.now()),
    )

    op.create_table(
        'audit_logs',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('staff_id', sa.Integer(), sa.ForeignKey('staff_users.id'), nullable=False),
        sa.Column('action', sa.String(length=100), nullable=False),
        sa.Column('entity_type', sa.String(length=50), nullable=False),
        sa.Column('entity_id', sa.Integer(), nullable=True),
        sa.Column('before_json', sa.JSON(), nullable=True),
        sa.Column('after_json', sa.JSON(), nullable=True),
        sa.Column('ip_address', sa.String(length=45), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now()),
    )

    op.create_table(
        'settings',
        sa.Column('key', sa.String(length=100), primary_key=True),
        sa.Column('value', sa.Text(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now()),
        sa.Column('updated_by', sa.Integer(), sa.ForeignKey('staff_users.id'), nullable=True),
    )

    op.create_table(
        'expenses',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('amount', sa.Numeric(12, 2), nullable=False),
        sa.Column('category', sa.String(length=20), nullable=False),
        sa.Column('comment', sa.Text(), nullable=True),
        sa.Column('created_by', sa.Integer(), sa.ForeignKey('staff_users.id'), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now()),
    )


def downgrade() -> None:
    op.drop_table('expenses')
    op.drop_table('settings')
    op.drop_table('audit_logs')
    op.drop_table('notification_logs')
    op.drop_table('issuance_items')
    op.drop_table('issuance_orders')
    op.drop_table('unresolved_parcels')
    op.drop_index('ix_parcels_dushanbe_delivery_method', table_name='parcels_dushanbe')
    op.drop_index('ix_parcels_dushanbe_created_at', table_name='parcels_dushanbe')
    op.drop_index('ix_parcels_dushanbe_status', table_name='parcels_dushanbe')
    op.drop_index('ix_parcels_dushanbe_client_id', table_name='parcels_dushanbe')
    op.drop_index('ix_parcels_dushanbe_track_id', table_name='parcels_dushanbe')
    op.drop_table('parcels_dushanbe')
    op.drop_index('ix_parcels_china_created_at', table_name='parcels_china')
    op.drop_index('ix_parcels_china_track_id', table_name='parcels_china')
    op.drop_table('parcels_china')
    op.drop_table('tariffs')
    op.drop_index('ix_clients_full_name', table_name='clients')
    op.drop_index('ix_clients_phone', table_name='clients')
    op.drop_index('ix_clients_tps_code', table_name='clients')
    op.drop_index('ix_clients_telegram_id', table_name='clients')
    op.drop_table('clients')
    op.drop_table('staff_users')
    op.drop_table('warehouses')
