"""add issuance comment and custom_price

Revision ID: ccec0dee8aac
Revises: 
Create Date: 2026-06-12 15:14:09.535875
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ccec0dee8aac'
down_revision: Union[str, None] = '7488a0137a83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issuance_items', sa.Column('custom_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('issuance_orders', sa.Column('comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issuance_orders', 'comment')
    op.drop_column('issuance_items', 'custom_price')
    # ### end Alembic commands ###
